### ISSUE TITLE
Grafana server crashes after installing the plugin

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/datasource-plugin-influxdb-08#2]
I tried to instal the plugin using the grafana-cli. Grafana server does not come up anymore after the restart (Grafana 3.0.0-beta1). It recovers after I remove the plugin. Other plugin do work.

**This is the grafana server logging (not very informative on the root cause):**

2016/04/06 11:50:11 [I] Starting Grafana
2016/04/06 11:50:11 [I] Version: 3.0.0-beta1, Commit: v3.0-beta1+2-gdecede3, Build date: 2016-03-31 14:54:34 +0200 CEST
2016/04/06 11:50:11 [I] Configuration Info
Config files:

Command lines overrides:

Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins

2016/04/06 11:50:11 [I] Database: sqlite3
2016/04/06 11:50:11 [I] Migrator: Starting DB migration
2016/04/06 11:50:11 [I] Plugins: Scan starting
2016/04/06 11:50:11 [I] Plugins: Registering plugin InfluxDB 0.8.x
2016/04/06 11:50:11 [I] Plugins: Registering plugin SimpleJson
2016/04/06 11:50:11 [I] Plugins: Adding route /public/plugins/grafana-influxdb-08-datasource -> /var/lib/grafana/plugins/grafana-influxdb-08-datasource
2016/04/06 11:50:11 [I] Plugins: Adding route /public/plugins/grafana-simple-json-datasource -> /var/lib/grafana/plugins/grafana-simple-json-datasource/dist
2016/04/06 11:50:11 [I] Listen: http://0.0.0.0:3002
2016/04/06 11:50:44 [I] Completed 172.22.69.242 admin "GET / HTTP/1.1" 500 Internal Server Error 0 bytes in 8954us
2016/04/06 11:50:55 [I] Completed 172.22.69.242 admin "GET / HTTP/1.1" 500 Internal Server Error 0 bytes in 6286us
2016/04/06 11:51:00 [I] Completed 172.22.69.242 admin "GET / HTTP/1.1" 500 Internal Server Error 0 bytes in 4090us
2016/04/06 11:51:00 [I] Completed 172.22.69.242 admin "GET /favicon.ico HTTP/1.1" 404 Not Found 19 bytes in 540us

**This is the log after removing the plugins (the server return html pages), but my influxdb 08 datasource do not work:**

2016/04/06 11:54:50 [I] Starting Grafana
2016/04/06 11:54:50 [I] Version: 3.0.0-beta1, Commit: v3.0-beta1+2-gdecede3, Build date: 2016-03-31 14:54:34 +0200 CEST
2016/04/06 11:54:50 [I] Configuration Info
Config files:

Command lines overrides:

Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins

2016/04/06 11:54:50 [I] Database: sqlite3
2016/04/06 11:54:50 [I] Migrator: Starting DB migration
2016/04/06 11:54:50 [I] Plugins: Scan starting
2016/04/06 11:54:50 [I] Plugins: Registering plugin SimpleJson
2016/04/06 11:54:50 [I] Plugins: Adding route /public/plugins/grafana-simple-json-datasource -> /var/lib/grafana/plugins/grafana-simple-json-datasource/dist
2016/04/06 11:54:50 [I] Listen: http://0.0.0.0:3002
2016/04/06 11:55:00 [frontendsettings.go:52 getFrontendSettingsMap()] [E] Could not find plugin definition for data source: grafana-influxdb-08-datasource
2016/04/06 11:55:00 [frontendsettings.go:52 getFrontendSettingsMap()] [E] Could not find plugin definition for data source: grafana-influxdb-08-datasource
2016/04/06 11:55:00 [frontendsettings.go:52 getFrontendSettingsMap()] [E] Could not find plugin definition for data source: grafana-influxdb-08-datasource
2016/04/06 11:55:00 [frontendsettings.go:52 getFrontendSettingsMap()] [E] Could not find plugin definition for data source: grafana-influxdb-08-datasource

**Comment by daniellee** [comment]
How did you install the plugin? Did you use the [CLI tool](http://docs.grafana.org/plugins/installation/)? If you check the /var/lib/grafana/plugins/grafana-influxdb-08-datasource directory, does it contain a file called plugin.json? If so what does it contain?

**Comment by PaulKuiper** [comment]
Hi Daniel,

Yes, I used the CLI tool. 
The plugin directory contained a file called plugin.json and all other files. 
Operating system is CentOS 7

**Comment by PaulKuiper** [comment]
I removed Grafana from the PC and installed the new beta2. The plugin now does not chrash Grafana anymore. This issue can thus be closed. 

The plugin however does not work. Setting up a datasource with the exact same settings as in the old grafana resulted in a failed Test conection (and no data). The url that was send by plugin to the backend was very different:

> Old:   http://Url/db/**Database**/series?p=**Password**&q=list+series&u=**Username**
> New: http://Url/series?q=list+series

No Username, Password and Database was included in the URL.

**Comment by pasancario** [comment]
Hi @PaulKuiper , 

I'm having the same issue as you: and just created a new ticket referencing this specific problem. https://github.com/grafana/influxdb-08-datasource/issues/3

Any update on it?

**Comment by bergquist** [comment]
Im closing this issue
lets keep the discussion about the second problem in #3
