### ISSUE TITLE
loading the query editor for influxdb 0.8 doesn't work

### ISSUE THREAD

**Issue by azylman** [grafana/datasource-plugin-influxdb-08#4]
The plugin is named grafana-influxdb-08-datasource and it's installed into `plugins/grafana-influxdb-08-datasource`. However, there's a hardcoded reference in [query_ctrl.js](https://github.com/grafana/influxdb-08-datasource/blob/master/query_ctrl.js#L55) that assumes the plugin name is influxdb_08, which isn't correct. This causes grafana to request `/public/plugins/influxdb_08/partials/query.editor.html`, which 404s.

**Comment by pasancario** [comment]
Hi @azylman , 

I've modified what you commented and it work fine right now to get series and at least is functional. But, I cannot use any aggregation function in column names. Did you solve it too?

![image](https://cloud.githubusercontent.com/assets/811713/14823913/74c7b212-0bd4-11e6-8bd8-11b52dabce32.png)

Also, there is no Raw Query capability in this plugin version.

**Comment by azylman** [comment]
@pasancario I'm not seeing any problem with raw queries, and we use raw queries for most of our aggregations. Sorry!

**Comment by bergquist** [comment]
merged and added in 1.0.1 https://grafana.net/plugins/grafana-influxdb-08-datasource
