### ISSUE TITLE
Cannot Remove Query from Panel

### ISSUE THREAD

**Issue by pasancario** [grafana/datasource-plugin-influxdb-08#6]
It seems query cannot be removed from Panel once its created: 

![image](https://cloud.githubusercontent.com/assets/811713/14918263/2c528e70-0e23-11e6-8746-10c7b988c04c.png)

Neither with raw editor or enhanced

**Comment by bergquist** [comment]
@pasancario this was a bug in during beta. Is this still a problem?

**Comment by pasancario** [comment]
Yes, It's fixed now.
